CREATE TABLE IF NOT EXISTS `cidade` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `nome` varchar(100) NOT NULL,
  `descricao` varchar(500) NOT NULL,
  `estado_pais` varchar(45) NOT NULL,
  `foto` varchar(500) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `id_UNIQUE` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=latin1;

INSERT INTO `whereverigo`.`cidade`
(`id`,
`nome`,
`descricao`,
`estado_pais`,
`foto`)
VALUES
('1','Jericocara', 
'Uma cidade praiana rústica. Kitesurfe, windsurfe, capoeira e, é claro, simplesmente ficar deitado na praia são atividades populares',
'Ceará, Brasil',
'jericocara'),
('2','Guaramiranga',
'A 110 km da capital, omunicípio se destaca como destino turístico pelo clima frio ao longo de todo o ano, rica fauna, movimentada cena artística e importantes construções históricas',
'Ceará, Brasil',
'guaramiranga'),
('3','Galinhos',
'A 116km de Natal. Salinas naturais formando pirâmides e as praias como a do Farol, são lugares turísticos da cidade',
'Rio Grande do Norte, Brasil',
'galinhos'),
('4','Praia do Patacho',
'areias claras, água translúcida e coqueiros vistosos ao fundo. São quase desertas e perfeitas para um dia de sossego',
'Alagoas, Brasil',
'praia_do_patacho'),
('5','Bonito',
'Rios de águas transparentes, cachoeiras, grutas e cavernas. Fauna e flora exuberantes, com centenas de espécies de aves, mamíferos e répteis ocupando uma vegetação que mistura o Cerrado com a Mata Atlântica',
'Mato Grosso do Sul, Brasil',
'bonito'),
('6','Tiradentes',
'Em suas ruas coloniais calçadas com pedras pés-de-moleque, as igrejas do século 18 dividem a atenção com o preservado casario formado por sobrados que abrigam restaurantes, pousadas, antiquários e lojas de artesanato ',
'Minas Gerais, Brasil',
'tiradentes'),
('7','Ilha Bela',
'A ilha possui duas faces distintas: a face voltada para o continente é a mais urbanizada e populosa cujas praias são mais calmas, badaladas e poluídas. Já a face voltada para o oceano aberto é pouco habitada',
'São Paulo, Brasil',
'ilha_bela'),
('8','Praia do Rosa',
'A faixa de areia clara, em formato de meia-lua, tem somente dois quilômetros de extensão. Os complementos, entretanto, fazem da Praia do Rosa uma das mais charmosas do litoral catarinense',
'Santa Catarina, Brasil',
'praia_do_rosa'),
('9','Gramado',
'Gramado é encantadora e charmosa por natureza. Por suas ruas floridas, povo acolhedor e hospitaleiro, pelos detalhes de sua arquitetura europeia, sua ampla rede hoteleira e gastronômica',
'Rio Grande do Sul, Brasil',
'gramado'),
('10','Monte Verde',
'O isolamento em meio às montanhas da Serra da Mantiqueira, aliado à generosidade da natureza e a uma diversidade de restaurantes e passeios, é um convite a fugir da rotina muitas vezes tumultuada dos grandes centros',
'Minas Gerais, Brasil',
'monte_verde'),
('11','Fortaleza',
'A capital cearense mistura muitas coisas de que o brasileiro gosta: belezas naturais, cultura, música, diversão e uma culinária de tirar o chapéu. Parque Aquático Beach Park é muito bom para a família',
'Ceará, Brasil',
'fortaleza'),
('12','Serra Gaúcha',
'Um Brasil com cara de Europa te espera no sul do país, com paisagens de tirar o fôlego, gastronomia rica, muito vinho e – claro – o friozinho característico das montanhas, com direito a neve de vez em quando',
'Rio Grande do Sul, Brasil',
'serra_gaucha'),
('13', 'Foz do Iguaçu',
'Em meio às 270 quedas d`água do parque, a impressionante Garganta do Diabo reúne 14 cachoeiras e produz um “arco-íris eterno”, em dias de clima bom.',
'Paraná',
'foz_do_iguacu'),
('14','Belo Horizonte',
'A cidade é mundialmente conhecida e exerce significativa influência nacional e até internacional, seja do ponto de vista cultural, econômico ou político. Conta com importantes monumentos, parques e museus',
'Minas Gerais, Brasil',
'belo_horizonte'),
('15','Maragogi',
'Em meio a tantos atributos naturais, uma atração se destaca e extasia os visitantes em Maragogi. São os arrecifes de coral com flora e fauna riquíssimas. À 125km de Maceió',
'Alagoas, Brasil',
'maragogi'),
('16','Penha',
'A cidade possui o título de "Capital Nacional do Marisco", sendo nacionalmente conhecida por abrigar o famoso parque temático Beto Carrero World',
'Santa Catarina, Brasil',
'penha'),
('17','Olímpia',
'A cidade de Olímpia, é a mais nova Estância Turística do Estado de São Paulo, devido ao Parque Aquático Thermas dos Laranjais. A cidade está localizada na região do Aqüífero Guarani. Distante a 430 km da capital São Paulo',
'São Paulo, Brasil',
'olimpia'),
('18','Caldas Novas',
'Águas quentes do balneário, considerado a maior estância hidrotermal do mundo. Com temperaturas variando entre 30 e 57 graus, as centenas de piscinas dos hotéis e dos clubes atraem especialmente grupos da terceira idade e famílias',
'Goias, Brasil',
'caldas_novas'),
('19','Campos do Jordão',
'Também conhecida como a Suíça Brasileira, título este recebido principalmente pelo seu clima frio e por suas belas construções em estilo europeu, é um dos 15 municípios do estado de São Paulo classificados como: Estância Climática',
'São Paulo, Brasil',
'campos_do_jordao'),
('20','Bento Gonçalves',
'Conhecida como "capital brasileira do vinho", se configura como a maior produtora de uva do Rio Grande do Sul, e o maior produtor de vinhos e derivados de uva do Brasil',
'Rio Grande do Sul, Brasil',
'bento_goncalves'),
('21','Domingos Martins',
'O município se destaca no desenvolvimento do turismo de montanha, na agricultura e cultura (grande influência da imigração alemã',
'Rio Grande do Sul, Brasil',
'domingos_martin'),
('22','Itaipava',
'Temperaturas agradáveis da serra acompanhados de pousadas aconchegantes e restaurantes cinco estrelas, torna esse  destino perfeito  para quem busca conforto, boa mesa e tempo de sobra para ficar à toa',
'Rio de Janeiro, Brasil',
'itaipava'),
('23','Curitiba',
'Curitiba é a capital mais fria do país e dotada de muito charme. Com médias térmicas de 10ºC durante o Inverno, pode ser considerada um pedacinho da Europa no Brasil', 
'Paraná, Brasil',
'curitiba'),
('24','Visconde de Mauá',
'É destino de serra ideal para curtir o frio e admirar belas paisagens, cheia de vilas aconchegantes para hospedagem',
'Rio de Janeiro, Brasil',
'visconde_de_maua'),
('25', 'Canela',
'Une belas paisagens naturais e arquitetura urbana com forte influência germânical',
'Rio Grande do Sul, Brasil',
'canela'),
('26','São Joaquim',
'Mais de 20 mil habitantes, o município é uma das melhores escolhas para quem quer ter a chance de se deparar com neve no Brasil, contando ainda com a forte produção de vinhos e frutas',
'Santa Catarina, Brasil',
'sao_joaquim'),
('27','Cunha',
'Um dos poucos municípios paulistas considerados  estância climática, se destaca pelo toque caseiro e bucólico da região. A cidade é perfeita para quem, além do clima fresco e acolhedor, busca por aventura e contato com a natureza',
'SP, Brasil',
'cunha'),
('28', 'Santo Antônio do Pinhal',
'Cercado pelo verde e montanhas altas, a cidade mescla lugares relaxantes com ambientes próprios',
'São Paulo, Brasil',
'santo_antonio_do_pinhal'),
('29', 'Gravatá',
'Com temperaturas que podem chegar aos 10ºC no inverno, Gravatá é cercada por matas, piscinas naturais e cachoeiras',
'Pernambuco, Brasil',
'gravata'),
('30','Triunfo', 'Encantadora, pacata e cheia de charme, é considerada o oasis do sertão chegando a 8 graus no inverno',
'Pernambuco, Brasil',
'triunfo'),
('31','Carro Quebrado',
'Coqueirais, mar verde e as famosas falésias multicoloridas que contornam a orla fizeram da praia um dos destinos favoritos dos moradores de Maceió',
'Alagoas, Brasil',
'carro_quebrado'),
('32','Praia do Riacho Doce',
'Se localiza na divisa dos estados da Bahia e de Espírito Santo, no Brasil. É exatamente o riacho que dá nome ao local que divide os dois estados',
'Espirito Santo, Brasil',
'praia_do_riacho_doce'),
('33','Ilha de Boipeba',
'Lugar encantador e paradisíaco com praias de águas cristalinas e areias brancas todas muito bem preservadas, sem falar nas piscinas naturais em alto mar e na beira mar. É um sossego só',
'Bahia, Brasil',
'ilha_de_boipeba'),
('34','Miguel Pereira',
'O conjunto formado pela simplicidade do interior e pelas belezas naturais faz de Miguel Pereira um agradável refúgio de final de semana. A cidadezinha oferece ainda hospedagens confortáveis, boa mesa, atrativos culturais e cachoeiras cristalinas',
'Rio de Janeiro, Brasil',
'miguel_pereira'),
('35','Santa Tereza',
'Uma jóia ainda pouco conhecida da Serra Gaúcha, com natureza exuberante e construções históricas de arquitetura colonial italiana',
'Rio Grande do Sul, Brasil',
'santa_tereza'),
('36','Urubici',
'Lugar para saltos de asa delta e parapente não faltam. Até o arvorismo, já pode ser praticada na cidade. O cenário para liberar a adrenalina não poderia ser mais encantador - afinal, não é por acaso que Urubici ganhou o merecido apelido de "Terra de Tesouros"',
'Santa Catarina, Brasil',
'urubici'),
('37','Blumenau',
'Oktoberfest acontece em Blumenau desde 1984',
'Santa Catarina, Brasil',
'blumenau'),
('38','Nova Trento',
'Nova Trento é hoje a Capital Catarinense do Turismo Religioso, Cidade aconchegante, une o poder da fé com as atrações culturais italianas e as belezas naturais.',
'Santa Catarina, Brasil',
'nova_trento'),
('39','Boituva',
'Passeios de balão e paraquedismo são os carros chefes da cidade, localizada a 117km de São Paulo. Há outras opções como rafting, paraquedismo e paintball',
'São Paulo, Brasil',
'boituva'),
('40','Chapada Diamantina',
'São tantas as atrações que se pode optar entre visitar grutas, tomar banho de cachoeira, fazer trekking em antigas trilhas de garimpeiros, montar a cavalo ou praticar esportes e aventuras',
'Bahia, Brasil',
'chapada_diamantina'),
('41','PETAR',
'O Parque Estadual Turístico do Alto Ribeira é considerado uma das Unidades de Conservação mais importantes do mundo. Abriga a maior porção de Mata Atlântica preservada do Brasil e mais de 300 cavernas. É considerado patrimônio da humanidade, pela UNESCO',
'São Paulo, Brasil',
'petar'),
('42','Florianópolis',
'A cidade é a capital brasileira com maior pontuação do Índice de Desenvolvimento Humano (IDH), sua economia baseada na tecnologia da informação, no turismo e nos serviços. A cidade tem 42 praias',
'Santa Catarina, Brasil',
'florianopolis'),
('43','Pirenópolis',
'Pequena cidade do interior de Goiás, tombada como Patrimônio Nacional, que conserva seu aspecto antigo e bucólico, cercada de morros e cachoeiras. Um retrato vivo da história goian',
'Goias, Brasil',
'pirenopolis'),
('44','Olinda',
'O Centro Histórico de Olinda, também chamado de Cidade Alta, abrange a área histórica do município brasileiro de Olinda, no estado de Pernambuco. Quase um terço da área total do município é tombado',
'Pernambuco, Brasil',
'olinda'),
('45','Goias Velho',
'Goiás Velho, ou apenas cidade de Goiás foi reconhecida em 2001 pela UNESCO como Patrimônio Histórico Mundial',
'Goias, Brasil',
'goias_velho'),
('46','Antônio Prado',
'A cidade possui o maior e o mais completo conjunto arquitetônico da colonização italiana no Brasil, com 48 imóveis do centro urbano tombados pelo Instituto do Patrimônio Histórico e Artístico Nacional desde a década de 1980',
'Rio Grande do Sul, Brasil',
'antonio_prado'),
('47','Parque Nacional Serra da Capivara',
'Inscrito pela UNESCO na lista do Patrimônio Mundial. É um conjunto de chapadas e vales abrigam sítios arqueológicos com pinturas e gravuras rupestres, além de outros vestígios do cotidiano pré-histórico',
'Piaui, Brasil',
'parque_nacional_serra_da_capivara'),
('48','Farroupilha',
'Farroupilha é o berço da colonização italiana no Estado do Rio Grande do Sul, e maior produtor de kiwi do Brasil, além de sediar o maior santuário da fé católica do Estado consagrado a N. S. de Caravaggio ',
'Rio Grande do Sul, Brasil',
'farroupilha'),
('49','Laranjeiras',
'Cerca de 20km de Aracaju é considerada como sítio arqueológico a céu aberto. A região também foi destaque em importantes lutas em defesa da República e pela Abolição da Escravatura',
'Sergipe, Brasil',
'laranjeiras'),
('50','São Cristóvão',
'Quarta cidade mais antiga do Brasil, fica a 23km da capital Aracaju. Tem como símbolo a Praça São Francisco, que foi reconhecida como Patrimônio Cultural da Humanidade pela UNESCO',
'Sergipe, Brasil',
'sao_cristovao'),
('51','Canindé de São Francisco',
'Sua história, suas belas paisagens, o #velhochico e as formações rochosas fazem da cidade um destino incrível para qualquer um. Foi cenário para as novelas "Amores Roubados", "Cordel Encantado" e "Velho Chico"',
'Sergipe, Brasil',
'caninde_de_sao_francisco'),
('52','Nazaré da Mata',
'É conhecida como terra dos Maracatus. Não é apenas uma dança, uma brincadeira, mas uma tradição passada de pai para filho em que os passos, as cores perpassam uma aculturação milenar da história da região',
'Pernambuco, Brasil',
'nazare_da_mata'),
('53','Paraty',
'As construções de seus casarões e igrejas traduzem um estilo de época e os misteriosos símbolos maçônicos que enfeitam as suas paredes nos levam a imaginar como seria a vida no Brasil de antigamente',
'Rio de Janeiro, Brasil',
'paraty'),
('54','São Paulo',
'Conta com importantes monumentos, parques e museus, como o Memorial da América Latina, o Museu da Língua Portuguesa, o Museu do Ipiranga, o MASP, o Parque Ibirapuera, o Jardim Botânico de São Paulo e a avenida Paulista',
'São Paulo, Brasil',
'sao_paulo'),
('55','Salvador',
'A cidade é notável pela sua gastronomia, música e arquitetura. Sua área metropolitana é a mais rica do nordeste. A influência africana é forte nos aspectos culturais da cidade.',
'Bahia, Brasil',
'salvador'),
('56','Manaus',
'A cidade destaca-se como a principal metrópole da região e é a entrada natural para quem quer conhecer a Floresta.',
'Amazonas, Brasil',
'manaus'),
('57','Trindade',
'Possui a unica Basilica no Mundo dedicada ao Turismo Religioso, A Festa do Divino Pai Eterno é atualmente considerado o maior evento religioso do Centro-Oeste, atraindo mais de 1,5 milhões de pessoas por ano',
'Goiás, Brasil',
'trindade'),
('58','Brejo da Madre de Deus',
'Todos os anos, nas semanas que antecedem a Páscoa, realiza-se o espetáculo da Paixão de Cristo de Fazenda Nova, o evento é encenado no maior teatro ao ar livre do mundo.',
'Pernambuco, Brasil',
'brejo_da_madre_de_deus'),
('59','Aparecida do Norte',
'A cidade de Aparecida no interior de São Paulo é o destin de peregrinação religiosa da América Latina e foi intitulada como a capital da fé',
'São Paulo, Brasil',
'aparecida_do_norte'),
('60','Canindé',
'Pequena cidade do Ceará que atrai milhares de fiéis  para romaria, principalmente voltada a Basílica de São Francisco, construída no início do século XX.',
'Ceará, Brasil',
'caninde'),
('61','Bom Jesus da Lapa',
'Capital baiana da fé,  recebe romeiros durante todo o ano. No periodo mais movimentado chega a receber 1,5 milhão de visitantes. Uma das mais importantes romarias é a da Terra  ou das Missões, que começa em julho.',
'Bahia, Brasil',
'bom_jesus_da_lapa'),
('62','Uberaba',
'Uma das principais características é o turismo religioso que iniciou-se com o trabalho do médium Chico Xavier na década de 70.  Caravanas de todas as partes do País e até do exterior chegam à  cidade.',
'Minas Gerais, Brasil',
'uberaba'),
('63','Tibau do Sul',
'Tibau do Sul é um lugar onde a natureza, a paz e a tranqüilidade reinam em perfeita harmonia. Aqui a natureza exuberante garante dias de paz ao visitante.',
'Rio Grande do Norte, Brasil',
'tibau_do_sul'),
('64','São Miguel do Gostoso',
'É um destino perfeito para dias de sossego em um cenário maravilhoso. O Paraíso a ser descoberto por você.',
'Rio Grande do Norte, Brasil',
'sao_miguel_do_gostoso'),
('65','Fernando de Noronha',
'O paraíso existe, fica na Terra e tem nome e sobrenome: Fernando de Noronha. Com areias douradas, mar em tons de azul turquesa e verde esmeralda, corais, vida marinha esplendorosa, mata, formações rochosas...',
'Pernambuco, Brasil',
'fernando_de_noronha'),
('66','Tamandaré',
'Tamandaré possui, ao todo, cinco praias em sua orla marítima. A mais conhecida é a praia dos Carneiros. Entre os muitos pontos históricos, encontra-se o Forte de Santo Inácio um dos mais importantes marcos da história de Pernambuco.',
'Pernambuco, Brasil',
'tamandare'),
('67','Trancoso',
'Destinado às classes mais ricas, ali está instalado um dos hotéis da rede Club Mediterranée. Graças a esta afluência, também o artesanato tem se desenvolvido, com características primitivistas.',
'Bahia, Brasil',
'trancoso'),
('68','Península de Maraú',
'A Penísula de Maraú é um dos destinos mais belos e encantadores do Brasil. Praias, cachoeiras e muito natureza compõe o cenário perfeito.',
'Bahia, Brasil',
'peninsula_de_marau'),
('69','Morro de São Paulo',
'Atualmente suas praias são frequentadas por turistas de todo o Brasil e de outros países, os quais são Primeira, Segunda, Terceira, Quarta, Quinta (ou do Encanto), Gamboa, do Pontal e Garapuá.',
'Bahia, Brasil',
'morro_de_sao_paulo'),
('70','São Miguel dos Milagres',
'Um dos passeios de São Miguel dos Milagres é ir até o Santuário do peixe-boi-marinho, um dos poucos lugares do Brasil onde é possível ver o mamífero.',
'Alagoas, Brasil',
'sao_miguel_dos_milagres'),
('71','Maceió',
'As praias e os passeios são os principais atrativos turísticos da cidade. Fazer um passeio de jangada até as piscinas naturais de Pajuçara é obrigatório, bem como curtir o visual da Ponta Verde, com coqueiros para nenhum amante da natureza botar defeito. Jatiúca, com ondas mais fortes, é ideal para quem prefere mar mais agitado.',
'Alagoas, Brasil',
'maceio'),
('72','Ubatuba',
'Ubatuba é um destino ótimo para aproveitar um final de semana ou feriado prolongado.',
'São Paulo, Brasil',
'ubatuba'),
('73','Angra dos Reis',
'É um dos destinos turísticos mais famosos do Brasil, a região foi abençoada pela mãe natureza, abrigando nada mais, nada menos que 365 ilhas espalhadas pelo litoral em um mar com tons de verde cristalino.',
'Rio de Janeiro, Brasil',
'angra_dos_reis'),
('74','Arraial do Cabo',
'Ideal para a prática de mergulho, o ecoturismo é a base da economia cabista, não aproveitando-se a região para o desenvolvimento de aquacultura e maricultura.',
'Rio de Janeiro, Brasil',
'arraial_do_cabo'),
('75','Garopaba',
'Entre suas praias pode-se destacar Vigia, Ouvidor, Barra, Ferrugem, Siriú, Gamboa e Silveira. As praias são ótimas para a prática do surfe, trazendo surfistas do Brasil inteiro para desfrutarem de suas ondas.',
'Santa Catarina, Brasil',
'garopaba'),
('76','Imbituba',
'Possui praias importantes como a Praia do Rosa, considerada uma das 30 baías mais bonitas do mundo e a Praia da Vila, que além de beleza encantadora, formado por ilhas próximas uma das outras e trilhas como a Trilha Ecológica do Farol.',
'Santa Catarina, Brasil',
'imbituba');



